name: Security Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks secret scan
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true

      - name: Run Semgrep scan
        uses: semgrep/semgrep-action@v1
        with:
          config: auto
        continue-on-error: true

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
        continue-on-error: true

      - name: Build Docker image
        run: docker build -t secure-devsecops-app .

      - name: Run Trivy container scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-devsecops-app
          severity: HIGH,CRITICAL
        continue-on-error: true