name: Security Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks secret scan
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep security rules 
        run: semgrep --config=p/security-audit --config=p/python --sarif --output=semgrep-results.sarif .
        continue-on-error: true 

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep-results.sarif  

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run pip-audit dependency scan     
        run: pip-audit -r requirements.txt
        continue-on-error: true

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "secure-devsecops-pipeline"
          path: "."
          format: "HTML"
          out: "dependency-check-report"
        continue-on-error: true

      - name: Upload OWASP Dependency-Check report 
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: dependency-check-report       
  
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          format: sarif
          output: trivy-fs-results.sarif
        continue-on-error: true

      - name: Upload Trivy filesystem report 
        uses: actions/upload-artifact@v4
        with:
          name: trivy-filesystem-results
          path: trivy-fs-results.sarif

      - name: Build Docker image
        run: docker build -t secure-devsecops-app .

      - name: Run Trivy container scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-devsecops-app
          severity: HIGH,CRITICAL
          format: sarif
          output: trivy-container-results.sarif
        continue-on-error: true

      - name: Upload Trivy container report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-container-results
          path: trivy-container-results.sarif   